# Python Assignment 3

#### Task 1: Write a function to compute 5/0 and use try/except to catch the exceptions.

In [32]:
def compute():
    return 5/0

try:
    compute()
##An ZeroDivisionError Exception - divide by zero is thrown and this function will never executed

except ZeroDivisionError as e:
    print("Oops! 'Zero Division Error' occured.")

finally:
    print('Reached finally block to cleanup')

Oops! 'Zero Division Error' occured.
Reached finally block to cleanup


#### 2. Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
    Hint: Subject,Verb and Object should be declared in the program as shown below.
    subjects=["Americans ","Indians"]
    verbs=["play","watch"]
    objects=["Baseball","Cricket"]

In [33]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

My_sentences=[(sub +" "+ ver +" " + obj) for sub in subjects for ver in verbs for obj in objects] 
for sentence in My_sentences: print(sentence)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


#### Task 2: 1.Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [31]:
#creating a output matrix where columns based on input vector(N)

import numpy as np 

x=np.array([1,2,3,4,5]) 
N=5 
matrix = np.column_stack([x**(N-i-1) 
for i in range(N)]) 
print(matrix) 

print("\t")
#Same Vandermonde matrix output is created using np.vander function in numpy

import numpy as np 

x=np.array([1,2,3,4,5]) 
N=5 
matrix1 = np.vander(x,N,increasing=False) 
print(matrix1) 


[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
	
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


## End of Assignment 3